/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.javaproj;

import java.util.Scanner;
import java.util.ArrayList;

public class App {
    
    static Scanner input = new Scanner(System.in);
    static ArrayList<student> students = new ArrayList<>();

    public static void main(String[] args) {
        
        int choice;

        do {
            System.out.println("======== Quiz Game =======");
            System.out.println("1-Start the quiz");
            System.out.println("2-Show all students");
            System.out.println("3-Show top student");
            System.out.println("4-Show average score");
            System.out.println("5-Exit");

            System.out.println("Enter your choice ( A number from 1 to 5) :");
            if(input.hasNextInt()){
                choice = input.nextInt();
                if(choice<1||choice>5){
                    System.out.println("Invalid choice! please enter a number from 1 to 5");
                    choice = 0;
                }
            }else{
                System.out.println("Invalid choice! please enter a number from 1 to 5");
                input.next();
                choice = 0;
            }
         
           

            switch (choice) {
                case 1:
                    Startquiz();
                    break;
                case 2:
                    ShowAllStudents();
                    break;
                case 3:
                    ShowTopStudent();
                    break;
                case 4:
                    ShowAverageScore();
                    break;
                case 5:
                    System.out.println("Good bye!");
                    break;
                default:
                    System.out.println("Invalid choice!");
            }

        } while (choice != 5);
    }

    public static void Startquiz() {
        System.out.println("Enter your name:");
        input.nextLine();
        String n = input.nextLine();

        System.out.println("Choose the category: ");
        System.out.println("1-Math");
        System.out.println("2-Ai");
        System.out.println("3-General knowledge");
         System.out.println("Enter your choice ( A number from 1 to 3) :");
        int c = input.nextInt();
        String category = "";

        if (c == 1)
            category = "Math";
        else if (c == 2)
            category = "Ai";
        else if (c == 3)
            category = "General knowledge";
        else {
            System.out.println("Invalid choice!");
            return; 
        }

        int score = Askquestions(category);

        student N = new student();
        N.set_name(n);
        N.set_score(score);
        N.set_category(category);
        students.add(N);

        System.out.println("Student " + N.get_name() + " is added to quiz with score: " + N.get_score());
    }

    public static void ShowAllStudents() {
        if (students.isEmpty()) {
            System.out.println("No students yet");
            return;
        }
        System.out.println("List of students:");
        for (student s : students) {
            System.out.println(s.get_name() + " Score= " + s.get_score() + " Category: " + s.get_category());
        }
    }

    public static void ShowTopStudent() {
        int top;
        if (students.isEmpty()) {
            System.out.println("No students yet!");
            return;
        }
        top = students.get(0).get_score();
        for (student s : students) {
            if (s.get_score() > top) {
                top = s.get_score();
            }
        }
        System.out.println("Top student(s) with score " + top + ":");
        for(student s : students){
            if(s.get_score()== top){
                System.out.println(s.get_name());
            }
        }
    }

    public static void ShowAverageScore() {
        if (students.isEmpty()) {
            System.out.println("No students yet!");
            return;
        }
        int sum = 0;
        for (student s : students) {
            sum += s.get_score();
        }
        double average = (double) sum / students.size();
        System.out.println("Average score = " + average);
    }

    public static int Askquestions(String category) {
        int score = 0;

        if (category.equals("Math")) {
            System.out.println("11 x 13 = ?");
            System.out.println("1) 140  2) 149  3) 143");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            int answer = input.nextInt();
            if (answer == 3){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" 143 is the correct ");
            }
            System.out.println("556 / 2 = ?");
            System.out.println("1) 260  2) 278  3) 277");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            answer = input.nextInt();
            if (answer == 2){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" 278 is the correct ");
            }

            System.out.println("25 x 12 = ?");
            System.out.println("1) 300  2) 290  3) 400");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            answer = input.nextInt();
            if (answer == 1){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" 300 is the correct ");
            }

        } else if (category.equals("Ai")) {
            System.out.println("What does AI stand for?");
            System.out.println("1) Automated Internet  2) Artificial Intelligence  3) Advanced Information");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            int answer = input.nextInt();
            if (answer == 2){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" Artificial Intelligence is the correct ");
            }

            System.out.println("Name a popular AI language?");
            System.out.println("1) Python  2) Java  3) C++");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            answer = input.nextInt();
            if (answer == 1){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" Python is the correct ");
            }

                

            System.out.println("Which AI branch deals with understanding human language?");
            System.out.println("1) Computer Vision  2) Natural Language Processing  3) Robotics");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            answer = input.nextInt();
            if (answer == 2){
                score++;
                  System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" Natural Language Processing is the correct ");
            }

        } else if (category.equals("General knowledge")) {
            System.out.println("How many continents are on the Earth?");
            System.out.println("1) 7  2) 5  3) 6");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            int answer = input.nextInt();
            if (answer == 1){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" 7 is the correct ");
            }

            System.out.println("What is the capital of Egypt?");
            System.out.println("1) Alexandria  2) Giza  3) Cairo");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            answer = input.nextInt();
            if (answer == 3){
                score++;
                System.out.println("correct answer");
            }else{
                System.out.println("Wrong answer!");
            
                System.out.println(" Cairo is the correct ");
            }

            System.out.println("Who wrote \"Romeo and Juliet\"?");
            System.out.println("1) Charles Dickens  2) William Shakespeare  3) J.K. Rowling");
            System.out.println("Enter your Answer(choice number 1 or 2 or 3)");
            
            answer = input.nextInt();
            if (answer == 2){
                score++;
                System.out.println("correct answer");
            }
            else{
                System.out.println("Wrong answer!");
            
                System.out.println(" William Shakespeare is the correct ");
            }
        }else {
            System.out.println("Invalid category");
          }

        return score;
    
        
    }
}
